define(["jquery"], function($) {
    var menu = {
        "server-group": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜<br/>单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "rs-number"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜<br/>单2",
                "name": "submenu2",
                "url": "./html/classes.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "rs-number2"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜<br/>单3",
                "name": "submenu3",
                "url": "./html/groups.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "rs-number3"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜<br/>单4",
                "name": "submenu4",
                "url": "./html/servers.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "rs-number4"
            }

        ],
        "server-center": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜单2",
                "name": "submenu2",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜单3",
                "name": "submenu3",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜单4",
                "name": "submenu4",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }

        ],
        "class-center": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜单2",
                "name": "submenu2",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜单3",
                "name": "submenu3",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜单4",
                "name": "submenu4",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }

        ],
        "administrator-area": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜单2",
                "name": "submenu2",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜单3",
                "name": "submenu3",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜单4",
                "name": "submenu4",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }

        ],
        "stream-discript": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜单2",
                "name": "submenu2",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜单3",
                "name": "submenu3",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜单4",
                "name": "submenu4",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }

        ],
        "wait-thing": [{
                "smid": 11,
                "pmid": 1,
                "text": "子菜单1",
                "name": "submenu1",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 12,
                "pmid": 1,
                "text": "子菜单2",
                "name": "submenu2",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 13,
                "pmid": 1,
                "text": "子菜单3",
                "name": "submenu3",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }, {
                "smid": 14,
                "pmid": 1,
                "text": "子菜单4",
                "name": "submenu4",
                "url": "./html/administrator.html",
                "sub-menu-cls": "submenu1",
                "fn-cls": "fn-cls",
                "icon-cls": "icon-cls"
            }

        ]
    };
    return menu;
})